const Images = [
    {
        id:101,
        url:'/plans/pop/pop.jpg',
        name:'pop',
    },
    {
        id:102,
        url:'/plans/pop/pop2.jpg',
        name:'pop1',
    },
    {
        id:103,
        url:'/plans/pop/pop3.jpg',
        name:'pop3',
    },
    {
        id:104,
        url:'/plans/pop/pop4.jpg',
        name:'pop4',
    },
    {
        id:105,
        url:'/plans/pop/pop5.jpg',
        name:'pop5',
    },
    {
        id:106,
        url:'/plans/pop/pop6.jpg',
        name:'pop6',
    },
    {
        id:107,
        url:'/plans/pop/pop7.jpg',
        name:'pop6',
    },
    {
        id:108,
        url:'/plans/pop/pop8.jpg',
        name:'pop6',
    },
    {
        id:109,
        url:'/plans/pop/pop9.jpg',
        name:'pop6',
    },
    {
        id:110,
        url:'/plans/pop/pop10.jpg',
        name:'pop6',
    },
]

export default Images;