const Images = [
    {
        id:101,
        url:'/plans/exterior/house-plan.jpg',
        name:'house-plan',
    },
    {
        id:102,
        url:'/plans/exterior/house-plan2.jpg',
        name:'house-plan1',
    },
    {
        id:103,
        url:'/plans/exterior/house-plan3.jpg',
        name:'house-plan3',
    },
    {
        id:104,
        url:'/plans/exterior/house-plan4.jpg',
        name:'house-plan4',
    },
    {
        id:105,
        url:'/plans/exterior/house-plan5.jpg',
        name:'house-plan5',
    },
    {
        id:106,
        url:'/plans/exterior/house-plan6.jpg',
        name:'house-plan6',
    },
    {
        id:107,
        url:'/plans/exterior/house-plan7.jpg',
        name:'house-plan7',
    },
    {
        id:108,
        url:'/plans/exterior/house-plan8.jpg',
        name:'house-plan8',
    },
    {
        id:109,
        url:'/plans/exterior/house-plan9.jpg',
        name:'house-plan9',
    },
    {
        id:110,
        url:'/plans/exterior/house-plan10.jpg',
        name:'house-plan10',
    },
]

export default Images;